name: Test and Build Workflow
# This workflow is triggered on pull requests to main branch
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:
    # Job name
    name: Build Replication plugin
    runs-on: ubuntu-latest
    steps:
      # This step uses the setup-java Github action: https://github.com/actions/setup-java
      - name: Set Up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # dependencies: OpenSearch
      - name: Checkout OpenSearch
        uses: actions/checkout@v2
        with:
          # TODO: Point to opensearch repo after the patch changes have been merged.
          repository: 'soosinha/OpenSearch'
          #repository: 'opensearch-project/OpenSearch'
          path: OpenSearch
          ref: 'ccr'
      - name: Build OpenSearch
        working-directory: ./OpenSearch
        run: |
          ./gradlew publishToMavenLocal
      # dependencies: common-utils
      - name: Checkout common-utils
        uses: actions/checkout@v2
        with:
          ref: 'main'
          repository: 'opensearch-project/common-utils'
          path: common-utils
      - name: Build common-utils
        working-directory: ./common-utils
        run: ./gradlew publishToMavenLocal -Dopensearch.version=1.1.0-SNAPSHOT
      # This step uses the checkout Github action: https://github.com/actions/checkout
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Build and run Replication tests
        run: |
          ./gradlew clean release
      - name: Upload failed logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs
          path: |
            build/testclusters/integTest-*/logs/*
            build/testclusters/leaderCluster-*/logs/*
            build/testclusters/followCluster-*/logs/*
      - name: Uploads coverage
        uses: codecov/codecov-action@v1.2.1
